---
title: "Analysis"
output: flexdashboard::flex_dashboard
date: "2026-01-31"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
library(dplyr)
library(inspectdf)
knitr::opts_chunk$set(echo = TRUE)
```

# Sierra_leone Ebola Cases by District

```{r load_data, include=FALSE}
ebola_sierra_leone <- read.csv(here("data", "ebola_sierra_leone.csv"))

```

```{r District_summary, echo=FALSE}
district_tab <- janitor::tabyl(ebola_sierra_leone,district)
district_tab_arranged <- arrange(district_tab,n)
district_tab_arranged
```

# Categories Plot

```{r categ_vars_plot, echo=FALSE}
categ_vars_plot <- show_plot(inspectdf::inspect_cat(ebola_sierra_leone)) 
categ_vars_plot
```

# Sierra_leone Car Analysis

**These are Sierra_leone favorite Cars:**

-   Toyota Prado
-   Mitsubishi Pajero
-   BMW X5

*You can see more different options* [here](https://www.autotrader.co.za/cars-for-sale?gclid=Cj0KCQiA-YvMBhDtARIsAHZuUzJ9DJNuf4XXR8qZAd9I_B0cowXqTwVqu07MkmHhciabZEu1R_Z81_4aAkgPEALw_wcB)

```{r cars_summary, echo=FALSE}
summary(cars)
```

# Car Perfomance Plots

**This is the plot for cars**:

```{r cars_plot, echo=FALSE}
plot(cars)
```


